kind: pipeline
type: kubernetes
name: default

helm_deploy: &helm_deploy
  mode: upgrade
  wait_for_upgrade: true
  atomic: true
  cleanup_failed_upgrade: true
  reuse_values: true

steps:
  # BUILD OCI IMAGE
  - name: docker
    image: harbor.v2.dcas.dev/infra/drone-kaniko:dcas-dev
    pull: always
    depends_on:
      - helm_lint
    settings:
      registry: harbor.v2.dcas.dev
      repo: dcas.dev/fav2
      tags:
        - latest
        - ${DRONE_BRANCH/\//-}
        - ${DRONE_COMMIT_SHA}
    # LINT HELM CHART
  - name: helm_lint
    image: harbor.v2.dcas.dev/djcass44/drone-helm3
    settings:
      mode: lint
      chart: ./fav-helm
    # DEPLOY TO DEV
  - name: deploy_development
    image: harbor.v2.dcas.dev/infra/drone-helm3:development
    depends_on:
      - helm_lint
      - docker
    settings:
      <<: *helm_deploy
      namespace: development
      release: fav2
      chart: ./fav-helm
      values:
        - ingress.enabled=true
        - ingress.host=icon-dev.v2.dcas.dev
        - image.tag=${DRONE_COMMIT_SHA}
        - spring.profile=development
    # DEPLOY TO PROD
  - name: deploy_production
    image: harbor.v2.dcas.dev/infra/drone-helm3:production
    depends_on:
      - helm_lint
      - docker
    settings:
      <<: *helm_deploy
      namespace: production
      release: fav2
      chart: ./fav-helm
      values:
        - ingress.enabled=true
        - ingress.host=icon.v2.dcas.dev
        - image.tag=${DRONE_BRANCH}
        - spring.profile=production
        - resources.requests.memory=250Mi
        - resources.limits.memory=500Mi
    when:
      branch:
        - master
trigger:
  when:
    event: push