kind: pipeline
type: kubernetes
name: default

helm_deploy: &helm_deploy
  mode: upgrade
  release: fav2
  chart: ./fav-helm
  wait_for_upgrade: true
  atomic: true
  cleanup_failed_upgrade: true
  reuse_values: true
  kube_api_server: https://kubernetes.default
  kube_certificate:
    from_secret: kube_certificate
  client_certificate_data:
    from_secret: client_certificate_data
  client_key_data:
    from_secret: client_key_data

steps:
  # BUILD DOCKER IMAGE
  - name: docker
    image: plugins/docker
    settings:
      registry: harbor.v2.dcas.dev
      repo: harbor.v2.dcas.dev/dcas.dev/fav2
      tags:
        - ${DRONE_BRANCH/\//-}
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    # LINT HELM CHART
  - name: helm_lint
    image: harbor.v2.dcas.dev/djcass44/drone-helm3
    settings:
      mode: lint
      chart: ./fav-helm
    # DEPLOY TO DEV
  - name: deploy_development
    image: harbor.v2.dcas.dev/djcass44/drone-helm3
    depends_on:
      - helm_lint
      - docker
    settings:
      <<: *helm_deploy
      namespace: development
      values:
        - ingress.enabled=true
        - ingress.host=icon-dev.v2.dcas.dev
        - image.tag=${DRONE_COMMIT_SHA}
        - spring.profile=development
        - persistence.storageClassName=nfs
    when:
      branch:
        exclude: master
    # DEPLOY TO PROD
  - name: deploy_production
    image: harbor.v2.dcas.dev/djcass44/drone-helm3
    depends_on:
      - helm_lint
      - docker
    settings:
      <<: *helm_deploy
      namespace: production
      values:
        - ingress.enabled=true
        - ingress.host=icon.v2.dcas.dev
        - image.tag=${DRONE_BRANCH}
        - spring.profile=production
        - persistence.storageClassName=nfs
        - replicas=2
    when:
      branch:
        - master
trigger:
  when:
    event: push