name: fav2

replicas: 1

# PVC to use
claimName: fav

# arbitrary environment variables to inject to the API pod
# this can be extended
env:
  FAV_PATH: "/data"
  FAV_INSECURE: false
  FAV_URL: "https://icon.jmp.castive.dev"
  CACHE_LIMIT: 60
  CACHE_DELAY: 10000
  SERVER_PORT: 8080

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 250Mi


images:
  api:
    repository: "docker.io/djcass44/fav2"
    tag: latest
    pullPolicy: Always

ingress:
  enabled: true
  host: icon.jmp.castive.dev
  # enforce HTTPS using HSTS (recommended)
  hsts: false


# network policy
netsec:
  enabled: true
  # label to allow traffic from
  source:
    app: traefik
  namespace:
    dev.dcas.netsec/name: kube-system