name: fav2

replicas: 1
imagePullSecrets:
  - name: v2-dcas.dev

# PVC to use
persistence:
#  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  storage: 1Gi
#  existingClaim: fav

spring:
  profile: local
  configUri: http://dcas-cloud-config.production.svc.cluster.local:8888

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 250Mi


podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsGroup: 1001
  runAsUser: 1001
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - ALL


image:
  repository: harbor.v2.dcas.dev/dcas.dev/fav2
  tag: latest
  pullPolicy: Always

ingress:
  enabled: false
  annotations:
    ingress.kubernetes.io/frame-deny: "true"
    ingress.kubernetes.io/hsts-max-age: "31536000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-preload: "true"
    ingress.kubernetes.io/referrer-policy: "no-referrer"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: icon.v2.dcas.dev



nodeSelector: {}

tolerations: []

affinity: {}