apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 100
        runAsUser: 100
        runAsGroup: 101
      volumes:
      - name: tmp
        emptyDir: {}
      {{ if .Values.persistence.existingClaim }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
      {{ end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - env:
          - name: SPRING_CLOUD_CONFIG_ENABLED
            value: "true"
          - name: SPRING_CLOUD_CONFIG_URI
            value: {{ .Values.spring.configUri }}
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.spring.profile | quote }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        {{ if .Values.persistence.existingClaim }}
        - mountPath: /data
          name: data
        {{ end }}
        resources:
          {{ toYaml .Values.resources | nindent 12 }}
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
      restartPolicy: Always
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}