apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  sessionAffinity: "ClientIP"
  ports:
  - name: http
    port: {{ .Values.env.SERVER_PORT }}
    targetPort: {{ .Values.env.SERVER_PORT }}
  selector:
    app: {{ .Values.name }}